- id: org-policy-verify
  name: org-policy verify
  description: Enforce MULTI_DOCUMENT_ENTERPRISE_CODING_PRINCIPLES (P1..P18) and required docs.
  entry: org-policy-verify
  language: python
  pass_filenames: false
